name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip install pre-commit
        echo "Pre-commit installed at: $(which pre-commit)"
        echo "$(dirname $(which pre-commit))" >> $GITHUB_PATH
        make install
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
    - name: Run tests
      run: |
        pytest --cov=src --cov=tests --cov-branch --cov-report=term-missing --cov-fail-under=75
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true
