name: Build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Set up Python and Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          make install
        shell: bash
      - name: Run tests
        run: |
          pytest --cov=src --cov=tests --cov-branch --cov-report=term-missing --cov-fail-under=75
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
