name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract Version Number
        run: |
          echo "Extracting version from tag..."
          VERSION=${GITHUB_REF##*/}
          VERSION=${VERSION#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"
      - name: Update Python
        run: python -m pip install --upgrade pip build
      - name: Build project
        run: python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
        env:
          TWINE_USERNAME: "__token__"
